export const data = [
  {
    popularity: 28.14,
    vote_count: 212,
    video: false,
    poster_path: "/pO9Edq8mgp9kD3N6EkCGYLnIVaA.jpg",
    id: 2210,
    adult: false,
    backdrop_path: "/6qQZ54iVgQWOFaVWss77yHy8YHu.jpg",
    original_language: "en",
    original_title: "Earth Girls Are Easy",
    genre_ids: [35, 10402, 878],
    title: "Earth Girls Are Easy",
    vote_average: 5.5,
    overview:
      "In this musical comedy, Valerie is dealing with her philandering fiancé, Ted, when she finds that a trio of aliens have crashed their spaceship into her swimming pool. Once the furry beings are shaved at her girlfriend's salon, the women discover three handsome men underneath. After absorbing the native culture via television, the spacemen are ready to hit the dating scene in 1980s Los Angeles.",
    release_date: "1988-05-12",
  },
  {
    popularity: 18.881,
    id: 1649,
    video: false,
    vote_count: 644,
    vote_average: 6.2,
    title: "Bill & Ted's Bogus Journey",
    release_date: "1991-07-19",
    original_language: "en",
    original_title: "Bill & Ted's Bogus Journey",
    genre_ids: [12, 35, 14, 878, 10402],
    backdrop_path: "/o2pdZNPYjoeeJG0tYzGjr8Qi1vt.jpg",
    adult: false,
    overview:
      "Amiable slackers Bill and Ted are once again roped into a fantastical adventure when De Nomolos, a villain from the future, sends evil robot duplicates of the two lads to terminate and replace them. The robot doubles actually succeed in killing Bill and Ted, but the two are determined to escape the afterlife, challenging the Grim Reaper to a series of games in order to return to the land of the living.",
    poster_path: "/tldtDfLnPFOtTWp758EmIP2Hbz5.jpg",
  },
  {
    popularity: 13.359,
    vote_count: 352,
    video: false,
    poster_path: "/atUtWrDlLzT1yeVK2EoYtvbS963.jpg",
    id: 11827,
    adult: false,
    backdrop_path: "/mn05NkblvY3Alnas3nGmaQt85v5.jpg",
    original_language: "en",
    original_title: "Heavy Metal",
    genre_ids: [12, 16, 14, 10402, 878],
    title: "Heavy Metal",
    vote_average: 6.3,
    overview:
      "A glowing orb terrorizes a young girl with a collection of stories of dark fantasy, eroticism and horror.",
    release_date: "1981-08-07",
  },
  {
    popularity: 10.151,
    vote_count: 200,
    video: false,
    poster_path: "/o4a7JkeSF2yItXz9Dj1HWNsfyfh.jpg",
    id: 14353,
    adult: false,
    backdrop_path: "/BdbfE3nPNCVI5rJHIlAAwDsulS.jpg",
    original_language: "en",
    original_title: "Repo! The Genetic Opera",
    genre_ids: [27, 10402, 878],
    title: "Repo! The Genetic Opera",
    vote_average: 6.4,
    overview:
      "By the year 2056, an epidemic of organ failures has devastated the planet. The megacorporation GeneCo provides organ transplants on a payment plan - and those who can’t fulfill their plans have their organs repossessed. In the midst of this, a sickly teenager discovers a shocking secret about herself, her father, and their connection to GeneCo.",
    release_date: "2008-07-18",
  },
  {
    popularity: 7.623,
    vote_count: 197,
    video: false,
    poster_path: "/AsvPgdcSlHocAbMp3yGZXjPiKKF.jpg",
    id: 11049,
    adult: false,
    backdrop_path: "/8TlMT5ZoLoGSX9u8ao6UVW3GFT9.jpg",
    original_language: "ja",
    original_title: "Interstella 5555: The 5tory of the 5ecret 5tar 5ystem",
    genre_ids: [12, 16, 10402, 878],
    title: "Interstella 5555: The 5tory of the 5ecret 5tar 5ystem",
    vote_average: 7.7,
    overview:
      "Four talented alien musicians are kidnapped by a record producer who disguises them as humans. Shep, a space pilot in love with bass player Stella, follows them to Earth. Reprogrammed to forget their real identities and renamed The Crescendolls, the group quickly becomes a huge success playing soulless corporate pop. At a concert, Shep manages to free all the musicians except Stella, and the band sets out to rediscover who they really are -- and to rescue Stella.",
    release_date: "2003-05-28",
  },
  {
    popularity: 3.207,
    id: 58520,
    video: false,
    vote_count: 5,
    vote_average: 4.2,
    title: "Live Freaky Die Freaky",
    release_date: "2006-01-31",
    original_language: "en",
    original_title: "Live Freaky Die Freaky",
    genre_ids: [16, 35, 10402, 878],
    backdrop_path: "/1hGrzTajJ5JC6VfPzrUj8Gj5t5k.jpg",
    adult: false,
    overview:
      "It is the year 3069 and the Earth has been robbed of all its natural resources, destroyed by war and ozone depletion.",
    poster_path: null,
  },
  {
    popularity: 3.133,
    vote_count: 0,
    video: false,
    poster_path: null,
    id: 282912,
    adult: false,
    backdrop_path: null,
    original_language: "en",
    original_title: "1984",
    genre_ids: [10402, 878],
    title: "1984",
    vote_average: 0,
    overview:
      'Inspired by one of the twentieth century\'s greatest novels, composer Lorin Maazel evokes Orwell\'s totalitarian nightmare, where "Big Brother" is always watching, and those guilty of "thoughtcrime" are condemned to face their worst fears in the infamous "Room 101". Filmed during world premiere performances of Robert Lepage\'s spectacular and psychologically gripping Royal Opera production and conducted by the composer, an international cast brings Orwell\'s datk vision to shattering operatic life.',
    release_date: "2008-05-12",
  },
  {
    popularity: 0.913,
    vote_count: 1,
    video: false,
    poster_path: null,
    id: 222060,
    adult: false,
    backdrop_path: null,
    original_language: "en",
    original_title: "Anonymous Celebrities: Animatic",
    genre_ids: [35, 18, 10402, 878, 53],
    title: "Anonymous Celebrities: Animatic",
    vote_average: 10,
    overview:
      "Nerdy Herbert meets Annie, the holier-than-thou girl of his dreams. But his plans for romance might be derailed by a nasty punk rocker, a mad scientist, obsessed federal agents... and mysterious aliens bent on destroying the planet!",
    release_date: "2005-10-18",
  },
  {
    popularity: 0.6,
    id: 690908,
    video: false,
    vote_count: 1,
    vote_average: 9,
    title: "John McCain & His Vegetable Friends",
    release_date: "2008-10-07",
    original_language: "en",
    original_title: "John McCain & His Vegetable Friends",
    genre_ids: [35, 16, 10402, 14, 878],
    backdrop_path: null,
    adult: false,
    overview:
      'John McCain is in what seems to be a car garage when his "vegetable friends" pay him a visit. They talk to him for a bit, and he decides to sing them a song, when everything starts to distort. His wife, Cindy, has to stop him.',
    poster_path: "/7qj7hsYNHUgLmxWIwHyK4JZQBKy.jpg",
  },
  {
    popularity: 0.651,
    vote_count: 2,
    video: false,
    poster_path: "/rr5IHVcHPAz5eWPR9YS8rjbfY4S.jpg",
    id: 565498,
    adult: false,
    backdrop_path: "/nd9G4qYYKUaAH4TtmraifasxyQm.jpg",
    original_language: "pt",
    original_title: "Eliana: É Dez",
    genre_ids: [35, 10402, 878],
    title: "É Dez",
    vote_average: 10,
    overview:
      '"É Dez" is the tenth studio album by Brazilian singer and presenter Eliana, released on August 30, 2002 by BMG, and produced by Guto Graça Mello. It was Eliana\'s first album to be released on DVD and VHS kit. It presents a story called "Eliana.com alegria", where Eliana is transported inside a computer and stay stuck there until the end of the story. There she meets several people, and also a Robot called "Ajuda".',
    release_date: "2002-08-30",
  },
];
